/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

public class App {

    public static void main(String[] args) {
        int year = Utils.defaultYear();
        int day = Utils.defaultDay();

        if(args.length != 0){
            day = intOrDie(args[0]);
        }

        int part = 1;
        if(args.length > 1){
            part = intOrDie(args[1]);
        }

        String input = Utils.readInput(year, day);
        Day dayInstance = Utils.getDayInstance(day);

        String result;
        if(part == 1) {
            result = dayInstance.part1(input);
        } else {
            result = dayInstance.part2(input);
        }

        System.out.println(result);
    }

    private static int intOrDie(String numeric) {
        try {
            return Integer.valueOf(numeric);
        } catch(NumberFormatException e) {
            System.out.println("The argument '" + numeric + "' could not be interpreted as an integer number.");
            System.exit(1);
        }
        return -1;
    }
}
